name: test_badge_gen
description: cli help generate test badge coverage svg
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  m_cli_core:
    path: ../m_cli_core
  args: ^2.6.0

dev_dependencies:
  test: ^1.21.0
  flutter_lints: ^3.0.0

executables:
  badge-test: main