name: test_badge_gen
description: cli help generate test badge coverage svg support customize the input and output file path for generated badges.
version: 0.0.1
homepage: https://github.com/MinhMark123123/m_cli
repository: https://github.com/MinhMark123123/m_cli
issue_tracker: https://github.com/MinhMark123123/m_cli/issues

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  m_cli_core: ^0.0.1
  args: ^2.6.0

dev_dependencies:
  test: ^1.21.0
  flutter_lints: ^3.0.0

executables:
  badge-test: main